# Generated by Django 2.2.2 on 2019-06-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20190622_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aritical',
            old_name='centent',
            new_name='content',
        ),
    ]
